# Configuração Simplificada para ComfyUI no Gitpod
tasks:
  - name: Setup ComfyUI
    init: |
      # Instala dependências do sistema
      sudo apt-get update && sudo apt-get install -y git-lfs python3-venv
      git lfs install
      # Cria e ativa ambiente virtual
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      # Instala PyTorch com a versão exata
      pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121
      # Instala as dependências do ComfyUI diretamente da raiz do repositório
      pip install -r requirements.txt
      pip install xformers accelerate transformers diffusers

    command: |
      source venv/bin/activate
      # Inicia o ComfyUI diretamente da raiz do repositório
      python3 main.py --listen --port 8188

ports:
  - port: 8188
    onOpen: open-browser # Abre o navegador automaticamente para o ComfyUI
  - port: 6006 # Porta para TensorBoard (ignorada)
    onOpen: ignore
