# Configuração para ComfyUI no Gitpod
tasks:
  - name: Setup ComfyUI
    init: |
      # Instala dependências do sistema
      sudo apt-get update && sudo apt-get install -y git-lfs python3-venv
      git lfs install
      # Cria e ativa ambiente virtual
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      # Instala PyTorch com uma versão compatível
      pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121
      # Verifica se a pasta ComfyUI existe e instala as dependências de dentro dela
      if [ -d "ComfyUI_windows_portable/ComfyUI" ]; then
        echo "Detectado ComfyUI_windows_portable/ComfyUI"
        pip install -r ComfyUI_windows_portable/ComfyUI/requirements.txt
      elif [ -d "ComfyUI" ]; then
        echo "Detectado ComfyUI"
        pip install -r ComfyUI/requirements.txt
      else
        echo "Erro: Nenhuma pasta ComfyUI ou ComfyUI_windows_portable/ComfyUI encontrada."
        exit 1
      fi
      pip install xformers accelerate transformers diffusers
    command: |
      source venv/bin/activate
      # Tenta entrar na pasta ComfyUI_windows_portable/ComfyUI
      if [ -d "ComfyUI_windows_portable/ComfyUI" ]; then
        echo "Executando ComfyUI de ComfyUI_windows_portable/ComfyUI"
        cd ComfyUI_windows_portable/ComfyUI
      elif [ -d "ComfyUI" ]; then
        echo "Executando ComfyUI de ComfyUI"
        cd ComfyUI
      else
        echo "Erro: Não foi possível encontrar o diretório para iniciar o ComfyUI."
        exit 1
      fi
      python3 main.py --listen --port 8188

ports:
  - port: 8188
    onOpen: open-browser # Abre o navegador automaticamente para o ComfyUI
  - port: 6006 # Porta para TensorBoard (ignorada)
    onOpen: ignore
