# Configuração para ComfyUI no Gitpod
tasks:
  - name: Setup ComfyUI
    init: |
      # Instala dependências do sistema
      sudo apt-get update && sudo apt-get install -y git-lfs python3-venv
      git lfs install

      # Cria e ativa ambiente virtual
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

      # Clona o ComfyUI diretamente para o workspace do Gitpod
      # NOTA: O ComfyUI será baixado para /workspace/comfyui/ComfyUI/
      git clone https://github.com/comfyanonymous/ComfyUI.git /workspace/comfyui/ComfyUI

      # Entra na pasta clonada e instala as dependências
      cd /workspace/comfyui/ComfyUI
      pip install -r requirements.txt
      # Instala PyTorch com a versão exata, para evitar conflitos
      pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121
      pip install xformers accelerate transformers diffusers
      cd /workspace/comfyui/ # Volta para a raiz do workspace

    command: |
      source venv/bin/activate
      # Inicia o ComfyUI da pasta clonada
      cd /workspace/comfyui/ComfyUI
      python3 main.py --listen --port 8188

ports:
  - port: 8188
    onOpen: open-browser # Abre o navegador automaticamente para o ComfyUI
  - port: 6006 # Porta para TensorBoard (ignorada)
    onOpen: ignore
